FROM python:3.9-slim


# Metadata labels
LABEL org.opencontainers.image.source=https://github.com/test-org-tbonelee/test-repo
LABEL org.opencontainers.image.description="GitHub Container for Testing Python 3.9 with R Environment"
